sudo: false
language: ruby
cache: bundler

before_install: gem install bundler -v 1.13.1
bundler_args: --jobs=3 --retry=3

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

  fast_finish: true
