sudo: false
language: ruby
cache: bundler

before_install: gem install bundler -v 1.13.1
bundler_args: --jobs=3 --retry=3

rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

  fast_finish: true
